version: '3.3'
services:
   db:
     image: mysql:8
     volumes:
       - /opt/test:/var/lib/mysql
       - /home/ubuntu/carbook.sql:/docker-entrypoint-initdb.d/carbook.sql
     environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_DATABASE: carbook
       MYSQL_USER: root
     ports:
       - 3306:3306
   web:
    image: tomcat:9-jdk11
    #image: tomcat:latest
    depends_on:
      - db
    volumes:
      - /home/ubuntu/target/demo-0.0.1-SNAPSHOT.jar:/usr/local/tomcat/webapps/demo-0.0.1-SNAPSHOT.jar
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: carbook
      MYSQL_USER: root
    ports:
      - 8080:8080
