version: '3.3'
services:
   db:
     image: mysql:5.7
     volumes:
       - /opt/test:/var/lib/mysql
       - /home/ubuntu/carbook.sql:/docker-entrypoint-initdb.d
     environment:
       MYSQL_DATABASE: carbook
       MYSQL_USER: root
     ports:
       - 3306:3306
   web:
    depends_on:
      - db
    image: tomcat
    volumes:
      - /home/ubuntu/target/demo-0.0.1-SNAPSHOT.jar:/usr/local/tomcat/webapps/demo-0.0.1-SNAPSHOT.jar
    ports:
      - '8082:8080'
    environment:
      MYSQL_DATABASE: carbook
      MYSQL_USER: root      
